#! /usr/bin/env bash

# YEAST // command programmed by shebangcode
# https://youtube.com/@ShebangCodeTeachesYou

showhelp() {
	echo "


                                                                                       kOOOO.
                                                                                      oMMMMW
               :oooo'    .ooooo.    .cdkKKKkd:        ,lxkKKKOkl.      'cdk0KK0kd,    NMMMMWoooooooo;
              'MMMMMl    oMMMMM.  :KMMMMMMMMMMNl    lNMMMMMMMMMMWk   :XMMMMMMMMMMMN, ,MMMMMMMMMMMMMMO
              oMMMMM.    XMMMMK .XMMMMNkooOMMMMMc  KMMMMXdccOMMMMM; oMMMMWocclWMMMMX kMMMMWooooooooo.
              XMMMM0    .MMMMM;.NMMMMN:''''NMMMMx .ddxkO,':cOMMMMM, xMMMMMkoc,cdlll; NMMMMx   'OOOOl
             'MMMMM,    oMMMMN oMMMMMMMMMMMMMMMMx .cxXWMMMMMMMMMMW   dWMMMMMMMMWKo. ,MMMMM.   OMMMMl
             oMMMMN     NMMMMd OMMMMXkkkkkkkkkkk':WMMMMWKkddMMMMMx    .:dOXWMMMMMMW kMMMM0   .WMMMM.
             KMMMMK...'kMMMMM' xMMMMX.   'kOOOO. WMMMMO.  .OMMMMM.'WWWWN'   .KMMMMM'XMMMMO..'0MMMMk
             xMMMMMMMMMMMMMMN  .WMMMMMXKWMMMMWo  MMMMMNOOXMMMMMMK .MMMMMMKKKXMMMMWo xMMMMMMMMMMMMO
              lXMMMMMMXMMMMMx   .dNMMMMMMMMKo.   lNMMMMMMMXWMMMMc  'kNMMMMMMMMMXd.   lXMMMMMMMWk,
           .0KKKNl''..lMMMMM.      .,::::'.        ';:::,. .''''      .,::::;'.        .;:::;.
           .MMMMMO:,cOMMMMMo
            dWMMMMMMMMMMMO,
             .xXWMMMMN0o'
                 ....



	 Light ack-based file searcher.

	Options.

	      -h ........... Shows this help message.
	-a <text> .......... Searches for hidden and normal files.                            
	-r <text> .......... Searches recursively in directories for files.                   
	-z <text> .......... Searches recursively in directories for hidden and normal files. 


	"
}

while getopts 'ha:r:z:' OPTION; do
	case "$OPTION" in
		h)
			showhelp
			exit 0;;
		a)
			dvalue="$OPTARG"
			sudo ls -a | sudo grep "$OPTARG"
			if [ -z "$OPTARG" ]; then
				echo "yeast: You must pass text for hidden file search."
				exit 1
			fi;;
		r)
			dvalue="$OPTARG"
			sudo ls --tree | sudo grep "$OPTARG"
			if [ -z "$OPTARG" ]; then
				echo "yeast: You must pass text for recursive file search."
				exit 1
			fi;;
		z)
			dvalue="$OPTARG"
			sudo ls --tree -a | sudo grep "$OPTARG"
			if [ -z "$OPTARG" ]; then
				echo "yeast: You must pass text for recursive hidden file search."
				exit 1
			fi;;
	esac
done

if [ -z "$1" ]; then
	echo "yeast: You must pass text for basic file search."
	exit 1
fi
sudo ls | sudo grep "$1"
